# This file is meant for compilation on Windows with MSVC. Use from a
# 'Visual Studio command-line' with:
#    nmake /f Makefile.win32
# See the Linux Makefile for details.
# Note that on x86 machines, Windows typically prohibits access to performance
# counter, so that the speed benchmark tool (speed_fndsa.exe) will not work,
# unless you add the '/DFNDSA_TSC=1' command-line option to make it use the
# timestamp counter, which is unreliable (see the Linux Makefile for details;
# in a nutshell, you must disable TurboBoost first), but at least does not
# crash.
CC = cl
CFLAGS = /nologo /W4 /O2
LD = cl
LDFLAGS = /nologo
LIBS =

OBJ_COMM = codec.obj mq.obj sha3.obj sysrng.obj util.obj
OBJ_KGEN = kgen.obj kgen_fxp.obj kgen_gauss.obj kgen_mp31.obj kgen_ntru.obj kgen_poly.obj kgen_zint31.obj
OBJ_SIGN = sign.obj sign_core.obj sign_fpoly.obj sign_fpr.obj sign_sampler.obj
OBJ_VRFY = vrfy.obj
OBJ = $(OBJ_COMM) $(OBJ_KGEN) $(OBJ_SIGN) $(OBJ_VRFY)
TESTOBJ = test_fndsa.obj
SPEEDOBJ = speed_fndsa.obj

all: test_fndsa.exe speed_fndsa.exe

clean:
	-del /Q $(OBJ) $(TESTOBJ) $(SPEEDOBJ) test_fndsa.exe speed_fndsa.exe

test_fndsa.exe: $(OBJ) $(TESTOBJ)
	$(LD) $(LDFLAGS) /Fe:test_fndsa.exe $(OBJ) $(TESTOBJ) $(LIBS)

speed_fndsa.exe: $(OBJ) $(SPEEDOBJ)
	$(LD) $(LDFLAGS) /Fe:speed_fndsa.exe $(OBJ) $(SPEEDOBJ) $(LIBS)

# -----------------------------------------------------------------------

codec.obj: codec.c fndsa.h inner.h
	$(CC) $(CFLAGS) /c /Fo:codec.obj codec.c

mq.obj: mq.c fndsa.h inner.h
	$(CC) $(CFLAGS) /c /Fo:mq.obj mq.c

sha3.obj: sha3.c fndsa.h inner.h
	$(CC) $(CFLAGS) /c /Fo:sha3.obj sha3.c

sysrng.obj: sysrng.c fndsa.h inner.h
	$(CC) $(CFLAGS) /c /Fo:sysrng.obj sysrng.c

util.obj: util.c fndsa.h inner.h
	$(CC) $(CFLAGS) /c /Fo:util.obj util.c

kgen.obj: kgen.c fndsa.h kgen_inner.h inner.h
	$(CC) $(CFLAGS) /c /Fo:kgen.obj kgen.c

kgen_fxp.obj: kgen_fxp.c fndsa.h kgen_inner.h inner.h
	$(CC) $(CFLAGS) /c /Fo:kgen_fxp.obj kgen_fxp.c

kgen_gauss.obj: kgen_gauss.c fndsa.h kgen_inner.h inner.h
	$(CC) $(CFLAGS) /c /Fo:kgen_gauss.obj kgen_gauss.c

kgen_mp31.obj: kgen_mp31.c fndsa.h kgen_inner.h inner.h
	$(CC) $(CFLAGS) /c /Fo:kgen_mp31.obj kgen_mp31.c

kgen_ntru.obj: kgen_ntru.c fndsa.h kgen_inner.h inner.h
	$(CC) $(CFLAGS) /c /Fo:kgen_ntru.obj kgen_ntru.c

kgen_poly.obj: kgen_poly.c fndsa.h kgen_inner.h inner.h
	$(CC) $(CFLAGS) /c /Fo:kgen_poly.obj kgen_poly.c

kgen_zint31.obj: kgen_zint31.c fndsa.h kgen_inner.h inner.h
	$(CC) $(CFLAGS) /c /Fo:kgen_zint31.obj kgen_zint31.c

sign.obj: sign.c fndsa.h sign_inner.h inner.h
	$(CC) $(CFLAGS) /c /Fo:sign.obj sign.c

sign_core.obj: sign_core.c fndsa.h sign_inner.h inner.h
	$(CC) $(CFLAGS) /c /Fo:sign_core.obj sign_core.c

sign_fpoly.obj: sign_fpoly.c fndsa.h sign_inner.h inner.h
	$(CC) $(CFLAGS) /c /Fo:sign_fpoly.obj sign_fpoly.c

sign_fpr.obj: sign_fpr.c fndsa.h sign_inner.h inner.h
	$(CC) $(CFLAGS) /c /Fo:sign_fpr.obj sign_fpr.c

sign_sampler.obj: sign_sampler.c fndsa.h sign_inner.h inner.h
	$(CC) $(CFLAGS) /c /Fo:sign_sampler.obj sign_sampler.c

vrfy.obj: vrfy.c fndsa.h inner.h
	$(CC) $(CFLAGS) /c /Fo:vrfy.obj vrfy.c

test_fndsa.obj: test_fndsa.c fndsa.h inner.h kgen_inner.h sign_inner.h
	$(CC) $(CFLAGS) /c /Fo:test_fndsa.obj test_fndsa.c

speed_fndsa.obj: speed_fndsa.c fndsa.h inner.h
	$(CC) $(CFLAGS) /c /Fo:speed_fndsa.obj speed_fndsa.c
